// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MediaAssetsColumns holds the columns for the "media_assets" table.
	MediaAssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeString},
		{Name: "b2_url", Type: field.TypeString},
		{Name: "capture_time", Type: field.TypeTime},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "geom", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// MediaAssetsTable holds the schema information for the "media_assets" table.
	MediaAssetsTable = &schema.Table{
		Name:       "media_assets",
		Columns:    MediaAssetsColumns,
		PrimaryKey: []*schema.Column{MediaAssetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mediaasset_user_id_capture_time",
				Unique:  false,
				Columns: []*schema.Column{MediaAssetsColumns[1], MediaAssetsColumns[3]},
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tag_user_id_name",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[1], TagsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MediaAssetsTable,
		TagsTable,
	}
)

func init() {
}
