// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"engram/api/ent/mediaasset"
	"engram/api/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaAssetUpdate is the builder for updating MediaAsset entities.
type MediaAssetUpdate struct {
	config
	hooks    []Hook
	mutation *MediaAssetMutation
}

// Where appends a list predicates to the MediaAssetUpdate builder.
func (_u *MediaAssetUpdate) Where(ps ...predicate.MediaAsset) *MediaAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *MediaAssetUpdate) SetFileKey(v string) *MediaAssetUpdate {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableFileKey(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *MediaAssetUpdate) SetMimeType(v string) *MediaAssetUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableMimeType(v *string) *MediaAssetUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetCaptureTime sets the "capture_time" field.
func (_u *MediaAssetUpdate) SetCaptureTime(v time.Time) *MediaAssetUpdate {
	_u.mutation.SetCaptureTime(v)
	return _u
}

// SetNillableCaptureTime sets the "capture_time" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableCaptureTime(v *time.Time) *MediaAssetUpdate {
	if v != nil {
		_u.SetCaptureTime(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *MediaAssetUpdate) SetLatitude(v float64) *MediaAssetUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableLatitude(v *float64) *MediaAssetUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *MediaAssetUpdate) AddLatitude(v float64) *MediaAssetUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *MediaAssetUpdate) ClearLatitude() *MediaAssetUpdate {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *MediaAssetUpdate) SetLongitude(v float64) *MediaAssetUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *MediaAssetUpdate) SetNillableLongitude(v *float64) *MediaAssetUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *MediaAssetUpdate) AddLongitude(v float64) *MediaAssetUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *MediaAssetUpdate) ClearLongitude() *MediaAssetUpdate {
	_u.mutation.ClearLongitude()
	return _u
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_u *MediaAssetUpdate) Mutation() *MediaAssetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaAssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaAssetUpdate) check() error {
	if v, ok := _u.mutation.FileKey(); ok {
		if err := mediaasset.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := mediaasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.mime_type": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaasset.Table, mediaasset.Columns, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(mediaasset.FieldFileKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CaptureTime(); ok {
		_spec.SetField(mediaasset.FieldCaptureTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(mediaasset.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(mediaasset.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(mediaasset.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(mediaasset.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(mediaasset.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(mediaasset.FieldLongitude, field.TypeFloat64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaAssetUpdateOne is the builder for updating a single MediaAsset entity.
type MediaAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaAssetMutation
}

// SetFileKey sets the "file_key" field.
func (_u *MediaAssetUpdateOne) SetFileKey(v string) *MediaAssetUpdateOne {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableFileKey(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *MediaAssetUpdateOne) SetMimeType(v string) *MediaAssetUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableMimeType(v *string) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetCaptureTime sets the "capture_time" field.
func (_u *MediaAssetUpdateOne) SetCaptureTime(v time.Time) *MediaAssetUpdateOne {
	_u.mutation.SetCaptureTime(v)
	return _u
}

// SetNillableCaptureTime sets the "capture_time" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableCaptureTime(v *time.Time) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetCaptureTime(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *MediaAssetUpdateOne) SetLatitude(v float64) *MediaAssetUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableLatitude(v *float64) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *MediaAssetUpdateOne) AddLatitude(v float64) *MediaAssetUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *MediaAssetUpdateOne) ClearLatitude() *MediaAssetUpdateOne {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *MediaAssetUpdateOne) SetLongitude(v float64) *MediaAssetUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *MediaAssetUpdateOne) SetNillableLongitude(v *float64) *MediaAssetUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *MediaAssetUpdateOne) AddLongitude(v float64) *MediaAssetUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *MediaAssetUpdateOne) ClearLongitude() *MediaAssetUpdateOne {
	_u.mutation.ClearLongitude()
	return _u
}

// Mutation returns the MediaAssetMutation object of the builder.
func (_u *MediaAssetUpdateOne) Mutation() *MediaAssetMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaAssetUpdate builder.
func (_u *MediaAssetUpdateOne) Where(ps ...predicate.MediaAsset) *MediaAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaAssetUpdateOne) Select(field string, fields ...string) *MediaAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaAsset entity.
func (_u *MediaAssetUpdateOne) Save(ctx context.Context) (*MediaAsset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaAssetUpdateOne) SaveX(ctx context.Context) *MediaAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaAssetUpdateOne) check() error {
	if v, ok := _u.mutation.FileKey(); ok {
		if err := mediaasset.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := mediaasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "MediaAsset.mime_type": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaAssetUpdateOne) sqlSave(ctx context.Context) (_node *MediaAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaasset.Table, mediaasset.Columns, sqlgraph.NewFieldSpec(mediaasset.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaasset.FieldID)
		for _, f := range fields {
			if !mediaasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(mediaasset.FieldFileKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(mediaasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CaptureTime(); ok {
		_spec.SetField(mediaasset.FieldCaptureTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(mediaasset.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(mediaasset.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(mediaasset.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(mediaasset.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(mediaasset.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(mediaasset.FieldLongitude, field.TypeFloat64)
	}
	_node = &MediaAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
