// Code generated by ent, DO NOT EDIT.

package ent

import (
	"engram/api/ent/mediaasset"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// MediaAsset is the model entity for the MediaAsset schema.
type MediaAsset struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// FileKey holds the value of the "file_key" field.
	FileKey string `json:"file_key,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// CaptureTime holds the value of the "capture_time" field.
	CaptureTime time.Time `json:"capture_time,omitempty"`
	// Latitude holds the value of the "latitude" field.
	Latitude *float64 `json:"latitude,omitempty"`
	// Longitude holds the value of the "longitude" field.
	Longitude *float64 `json:"longitude,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaAsset) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediaasset.FieldLatitude, mediaasset.FieldLongitude:
			values[i] = new(sql.NullFloat64)
		case mediaasset.FieldUserID, mediaasset.FieldFileKey, mediaasset.FieldMimeType:
			values[i] = new(sql.NullString)
		case mediaasset.FieldCaptureTime, mediaasset.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case mediaasset.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaAsset fields.
func (_m *MediaAsset) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediaasset.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case mediaasset.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case mediaasset.FieldFileKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_key", values[i])
			} else if value.Valid {
				_m.FileKey = value.String
			}
		case mediaasset.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case mediaasset.FieldCaptureTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field capture_time", values[i])
			} else if value.Valid {
				_m.CaptureTime = value.Time
			}
		case mediaasset.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				_m.Latitude = new(float64)
				*_m.Latitude = value.Float64
			}
		case mediaasset.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				_m.Longitude = new(float64)
				*_m.Longitude = value.Float64
			}
		case mediaasset.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaAsset.
// This includes values selected through modifiers, order, etc.
func (_m *MediaAsset) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MediaAsset.
// Note that you need to call MediaAsset.Unwrap() before calling this method if this MediaAsset
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaAsset) Update() *MediaAssetUpdateOne {
	return NewMediaAssetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaAsset entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaAsset) Unwrap() *MediaAsset {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaAsset is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaAsset) String() string {
	var builder strings.Builder
	builder.WriteString("MediaAsset(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("file_key=")
	builder.WriteString(_m.FileKey)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("capture_time=")
	builder.WriteString(_m.CaptureTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Latitude; v != nil {
		builder.WriteString("latitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Longitude; v != nil {
		builder.WriteString("longitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MediaAssets is a parsable slice of MediaAsset.
type MediaAssets []*MediaAsset
