// Code generated by ent, DO NOT EDIT.

package ent

import (
	"engram/api/ent/mediaasset"
	"engram/api/ent/schema"
	"engram/api/ent/tag"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mediaassetFields := schema.MediaAsset{}.Fields()
	_ = mediaassetFields
	// mediaassetDescUserID is the schema descriptor for user_id field.
	mediaassetDescUserID := mediaassetFields[1].Descriptor()
	// mediaasset.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	mediaasset.UserIDValidator = mediaassetDescUserID.Validators[0].(func(string) error)
	// mediaassetDescB2URL is the schema descriptor for b2_url field.
	mediaassetDescB2URL := mediaassetFields[2].Descriptor()
	// mediaasset.B2URLValidator is a validator for the "b2_url" field. It is called by the builders before save.
	mediaasset.B2URLValidator = mediaassetDescB2URL.Validators[0].(func(string) error)
	// mediaassetDescMimeType is the schema descriptor for mime_type field.
	mediaassetDescMimeType := mediaassetFields[4].Descriptor()
	// mediaasset.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	mediaasset.MimeTypeValidator = mediaassetDescMimeType.Validators[0].(func(string) error)
	// mediaassetDescCreatedAt is the schema descriptor for created_at field.
	mediaassetDescCreatedAt := mediaassetFields[6].Descriptor()
	// mediaasset.DefaultCreatedAt holds the default value on creation for the created_at field.
	mediaasset.DefaultCreatedAt = mediaassetDescCreatedAt.Default.(func() time.Time)
	// mediaassetDescID is the schema descriptor for id field.
	mediaassetDescID := mediaassetFields[0].Descriptor()
	// mediaasset.DefaultID holds the default value on creation for the id field.
	mediaasset.DefaultID = mediaassetDescID.Default.(func() uuid.UUID)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescUserID is the schema descriptor for user_id field.
	tagDescUserID := tagFields[1].Descriptor()
	// tag.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	tag.UserIDValidator = tagDescUserID.Validators[0].(func(string) error)
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[2].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	// tagDescID is the schema descriptor for id field.
	tagDescID := tagFields[0].Descriptor()
	// tag.DefaultID holds the default value on creation for the id field.
	tag.DefaultID = tagDescID.Default.(func() uuid.UUID)
}
