// Code generated by entproto. DO NOT EDIT.

// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file entpb.proto (package entpb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchCreateMediaAssetsRequest, BatchCreateMediaAssetsResponse, CreateMediaAssetRequest, DeleteMediaAssetRequest, GetMediaAssetRequest, ListMediaAssetRequest, ListMediaAssetResponse, MediaAsset, UpdateMediaAssetRequest } from "./entpb_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service entpb.MediaAssetService
 */
export const MediaAssetService = {
  typeName: "entpb.MediaAssetService",
  methods: {
    /**
     * @generated from rpc entpb.MediaAssetService.Create
     */
    create: {
      name: "Create",
      I: CreateMediaAssetRequest,
      O: MediaAsset,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc entpb.MediaAssetService.Get
     */
    get: {
      name: "Get",
      I: GetMediaAssetRequest,
      O: MediaAsset,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc entpb.MediaAssetService.Update
     */
    update: {
      name: "Update",
      I: UpdateMediaAssetRequest,
      O: MediaAsset,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc entpb.MediaAssetService.Delete
     */
    delete: {
      name: "Delete",
      I: DeleteMediaAssetRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc entpb.MediaAssetService.List
     */
    list: {
      name: "List",
      I: ListMediaAssetRequest,
      O: ListMediaAssetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc entpb.MediaAssetService.BatchCreate
     */
    batchCreate: {
      name: "BatchCreate",
      I: BatchCreateMediaAssetsRequest,
      O: BatchCreateMediaAssetsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

