// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MediaAsset is the predicate function for mediaasset builders.
type MediaAsset func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
