// Code generated by ent, DO NOT EDIT.

package mediaasset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the mediaasset type in the database.
	Label = "media_asset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldB2URL holds the string denoting the b2_url field in the database.
	FieldB2URL = "b2_url"
	// FieldCaptureTime holds the string denoting the capture_time field in the database.
	FieldCaptureTime = "capture_time"
	// FieldMimeType holds the string denoting the mime_type field in the database.
	FieldMimeType = "mime_type"
	// FieldGeom holds the string denoting the geom field in the database.
	FieldGeom = "geom"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the mediaasset in the database.
	Table = "media_assets"
)

// Columns holds all SQL columns for mediaasset fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldB2URL,
	FieldCaptureTime,
	FieldMimeType,
	FieldGeom,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// B2URLValidator is a validator for the "b2_url" field. It is called by the builders before save.
	B2URLValidator func(string) error
	// MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	MimeTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MediaAsset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByB2URL orders the results by the b2_url field.
func ByB2URL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldB2URL, opts...).ToFunc()
}

// ByCaptureTime orders the results by the capture_time field.
func ByCaptureTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaptureTime, opts...).ToFunc()
}

// ByMimeType orders the results by the mime_type field.
func ByMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMimeType, opts...).ToFunc()
}

// ByGeom orders the results by the geom field.
func ByGeom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeom, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
