// Code generated by ent, DO NOT EDIT.

package mediaasset

import (
	"engram/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUserID, v))
}

// FileKey applies equality check predicate on the "file_key" field. It's identical to FileKeyEQ.
func FileKey(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldFileKey, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// CaptureTime applies equality check predicate on the "capture_time" field. It's identical to CaptureTimeEQ.
func CaptureTime(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCaptureTime, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldLongitude, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldUserID, v))
}

// FileKeyEQ applies the EQ predicate on the "file_key" field.
func FileKeyEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldFileKey, v))
}

// FileKeyNEQ applies the NEQ predicate on the "file_key" field.
func FileKeyNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldFileKey, v))
}

// FileKeyIn applies the In predicate on the "file_key" field.
func FileKeyIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldFileKey, vs...))
}

// FileKeyNotIn applies the NotIn predicate on the "file_key" field.
func FileKeyNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldFileKey, vs...))
}

// FileKeyGT applies the GT predicate on the "file_key" field.
func FileKeyGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldFileKey, v))
}

// FileKeyGTE applies the GTE predicate on the "file_key" field.
func FileKeyGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldFileKey, v))
}

// FileKeyLT applies the LT predicate on the "file_key" field.
func FileKeyLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldFileKey, v))
}

// FileKeyLTE applies the LTE predicate on the "file_key" field.
func FileKeyLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldFileKey, v))
}

// FileKeyContains applies the Contains predicate on the "file_key" field.
func FileKeyContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldFileKey, v))
}

// FileKeyHasPrefix applies the HasPrefix predicate on the "file_key" field.
func FileKeyHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldFileKey, v))
}

// FileKeyHasSuffix applies the HasSuffix predicate on the "file_key" field.
func FileKeyHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldFileKey, v))
}

// FileKeyEqualFold applies the EqualFold predicate on the "file_key" field.
func FileKeyEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldFileKey, v))
}

// FileKeyContainsFold applies the ContainsFold predicate on the "file_key" field.
func FileKeyContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldFileKey, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldMimeType, v))
}

// CaptureTimeEQ applies the EQ predicate on the "capture_time" field.
func CaptureTimeEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCaptureTime, v))
}

// CaptureTimeNEQ applies the NEQ predicate on the "capture_time" field.
func CaptureTimeNEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldCaptureTime, v))
}

// CaptureTimeIn applies the In predicate on the "capture_time" field.
func CaptureTimeIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldCaptureTime, vs...))
}

// CaptureTimeNotIn applies the NotIn predicate on the "capture_time" field.
func CaptureTimeNotIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldCaptureTime, vs...))
}

// CaptureTimeGT applies the GT predicate on the "capture_time" field.
func CaptureTimeGT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldCaptureTime, v))
}

// CaptureTimeGTE applies the GTE predicate on the "capture_time" field.
func CaptureTimeGTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldCaptureTime, v))
}

// CaptureTimeLT applies the LT predicate on the "capture_time" field.
func CaptureTimeLT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldCaptureTime, v))
}

// CaptureTimeLTE applies the LTE predicate on the "capture_time" field.
func CaptureTimeLTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldCaptureTime, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldLatitude, v))
}

// LatitudeIsNil applies the IsNil predicate on the "latitude" field.
func LatitudeIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldLatitude))
}

// LatitudeNotNil applies the NotNil predicate on the "latitude" field.
func LatitudeNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldLatitude))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldLongitude, v))
}

// LongitudeIsNil applies the IsNil predicate on the "longitude" field.
func LongitudeIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldLongitude))
}

// LongitudeNotNil applies the NotNil predicate on the "longitude" field.
func LongitudeNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldLongitude))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.NotPredicates(p))
}
