// Code generated by ent, DO NOT EDIT.

package mediaasset

import (
	"engram/api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUserID, v))
}

// B2URL applies equality check predicate on the "b2_url" field. It's identical to B2URLEQ.
func B2URL(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldB2URL, v))
}

// CaptureTime applies equality check predicate on the "capture_time" field. It's identical to CaptureTimeEQ.
func CaptureTime(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCaptureTime, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// Geom applies equality check predicate on the "geom" field. It's identical to GeomEQ.
func Geom(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldGeom, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldUserID, v))
}

// B2URLEQ applies the EQ predicate on the "b2_url" field.
func B2URLEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldB2URL, v))
}

// B2URLNEQ applies the NEQ predicate on the "b2_url" field.
func B2URLNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldB2URL, v))
}

// B2URLIn applies the In predicate on the "b2_url" field.
func B2URLIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldB2URL, vs...))
}

// B2URLNotIn applies the NotIn predicate on the "b2_url" field.
func B2URLNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldB2URL, vs...))
}

// B2URLGT applies the GT predicate on the "b2_url" field.
func B2URLGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldB2URL, v))
}

// B2URLGTE applies the GTE predicate on the "b2_url" field.
func B2URLGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldB2URL, v))
}

// B2URLLT applies the LT predicate on the "b2_url" field.
func B2URLLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldB2URL, v))
}

// B2URLLTE applies the LTE predicate on the "b2_url" field.
func B2URLLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldB2URL, v))
}

// B2URLContains applies the Contains predicate on the "b2_url" field.
func B2URLContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldB2URL, v))
}

// B2URLHasPrefix applies the HasPrefix predicate on the "b2_url" field.
func B2URLHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldB2URL, v))
}

// B2URLHasSuffix applies the HasSuffix predicate on the "b2_url" field.
func B2URLHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldB2URL, v))
}

// B2URLEqualFold applies the EqualFold predicate on the "b2_url" field.
func B2URLEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldB2URL, v))
}

// B2URLContainsFold applies the ContainsFold predicate on the "b2_url" field.
func B2URLContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldB2URL, v))
}

// CaptureTimeEQ applies the EQ predicate on the "capture_time" field.
func CaptureTimeEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCaptureTime, v))
}

// CaptureTimeNEQ applies the NEQ predicate on the "capture_time" field.
func CaptureTimeNEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldCaptureTime, v))
}

// CaptureTimeIn applies the In predicate on the "capture_time" field.
func CaptureTimeIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldCaptureTime, vs...))
}

// CaptureTimeNotIn applies the NotIn predicate on the "capture_time" field.
func CaptureTimeNotIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldCaptureTime, vs...))
}

// CaptureTimeGT applies the GT predicate on the "capture_time" field.
func CaptureTimeGT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldCaptureTime, v))
}

// CaptureTimeGTE applies the GTE predicate on the "capture_time" field.
func CaptureTimeGTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldCaptureTime, v))
}

// CaptureTimeLT applies the LT predicate on the "capture_time" field.
func CaptureTimeLT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldCaptureTime, v))
}

// CaptureTimeLTE applies the LTE predicate on the "capture_time" field.
func CaptureTimeLTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldCaptureTime, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldMimeType, v))
}

// GeomEQ applies the EQ predicate on the "geom" field.
func GeomEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldGeom, v))
}

// GeomNEQ applies the NEQ predicate on the "geom" field.
func GeomNEQ(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldGeom, v))
}

// GeomIn applies the In predicate on the "geom" field.
func GeomIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldGeom, vs...))
}

// GeomNotIn applies the NotIn predicate on the "geom" field.
func GeomNotIn(vs ...string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldGeom, vs...))
}

// GeomGT applies the GT predicate on the "geom" field.
func GeomGT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldGeom, v))
}

// GeomGTE applies the GTE predicate on the "geom" field.
func GeomGTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldGeom, v))
}

// GeomLT applies the LT predicate on the "geom" field.
func GeomLT(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldGeom, v))
}

// GeomLTE applies the LTE predicate on the "geom" field.
func GeomLTE(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldGeom, v))
}

// GeomContains applies the Contains predicate on the "geom" field.
func GeomContains(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContains(FieldGeom, v))
}

// GeomHasPrefix applies the HasPrefix predicate on the "geom" field.
func GeomHasPrefix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasPrefix(FieldGeom, v))
}

// GeomHasSuffix applies the HasSuffix predicate on the "geom" field.
func GeomHasSuffix(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldHasSuffix(FieldGeom, v))
}

// GeomIsNil applies the IsNil predicate on the "geom" field.
func GeomIsNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIsNull(FieldGeom))
}

// GeomNotNil applies the NotNil predicate on the "geom" field.
func GeomNotNil() predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotNull(FieldGeom))
}

// GeomEqualFold applies the EqualFold predicate on the "geom" field.
func GeomEqualFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEqualFold(FieldGeom, v))
}

// GeomContainsFold applies the ContainsFold predicate on the "geom" field.
func GeomContainsFold(v string) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldContainsFold(FieldGeom, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MediaAsset {
	return predicate.MediaAsset(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MediaAsset) predicate.MediaAsset {
	return predicate.MediaAsset(sql.NotPredicates(p))
}
