// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: upload.proto

package rpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	rpc "engram/api/rpc"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UploadServiceName is the fully-qualified name of the UploadService service.
	UploadServiceName = "engram.upload.v1.UploadService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UploadServiceGetUploadURLProcedure is the fully-qualified name of the UploadService's
	// GetUploadURL RPC.
	UploadServiceGetUploadURLProcedure = "/engram.upload.v1.UploadService/GetUploadURL"
)

// UploadServiceClient is a client for the engram.upload.v1.UploadService service.
type UploadServiceClient interface {
	GetUploadURL(context.Context, *connect.Request[rpc.GetUploadURLRequest]) (*connect.Response[rpc.GetUploadURLResponse], error)
}

// NewUploadServiceClient constructs a client for the engram.upload.v1.UploadService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUploadServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UploadServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	uploadServiceMethods := rpc.File_upload_proto.Services().ByName("UploadService").Methods()
	return &uploadServiceClient{
		getUploadURL: connect.NewClient[rpc.GetUploadURLRequest, rpc.GetUploadURLResponse](
			httpClient,
			baseURL+UploadServiceGetUploadURLProcedure,
			connect.WithSchema(uploadServiceMethods.ByName("GetUploadURL")),
			connect.WithClientOptions(opts...),
		),
	}
}

// uploadServiceClient implements UploadServiceClient.
type uploadServiceClient struct {
	getUploadURL *connect.Client[rpc.GetUploadURLRequest, rpc.GetUploadURLResponse]
}

// GetUploadURL calls engram.upload.v1.UploadService.GetUploadURL.
func (c *uploadServiceClient) GetUploadURL(ctx context.Context, req *connect.Request[rpc.GetUploadURLRequest]) (*connect.Response[rpc.GetUploadURLResponse], error) {
	return c.getUploadURL.CallUnary(ctx, req)
}

// UploadServiceHandler is an implementation of the engram.upload.v1.UploadService service.
type UploadServiceHandler interface {
	GetUploadURL(context.Context, *connect.Request[rpc.GetUploadURLRequest]) (*connect.Response[rpc.GetUploadURLResponse], error)
}

// NewUploadServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUploadServiceHandler(svc UploadServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	uploadServiceMethods := rpc.File_upload_proto.Services().ByName("UploadService").Methods()
	uploadServiceGetUploadURLHandler := connect.NewUnaryHandler(
		UploadServiceGetUploadURLProcedure,
		svc.GetUploadURL,
		connect.WithSchema(uploadServiceMethods.ByName("GetUploadURL")),
		connect.WithHandlerOptions(opts...),
	)
	return "/engram.upload.v1.UploadService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UploadServiceGetUploadURLProcedure:
			uploadServiceGetUploadURLHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUploadServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUploadServiceHandler struct{}

func (UnimplementedUploadServiceHandler) GetUploadURL(context.Context, *connect.Request[rpc.GetUploadURLRequest]) (*connect.Response[rpc.GetUploadURLResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("engram.upload.v1.UploadService.GetUploadURL is not implemented"))
}
