// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: entpb.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMediaAssetRequest_View int32

const (
	GetMediaAssetRequest_VIEW_UNSPECIFIED GetMediaAssetRequest_View = 0
	GetMediaAssetRequest_BASIC            GetMediaAssetRequest_View = 1
	GetMediaAssetRequest_WITH_EDGE_IDS    GetMediaAssetRequest_View = 2
)

// Enum value maps for GetMediaAssetRequest_View.
var (
	GetMediaAssetRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetMediaAssetRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetMediaAssetRequest_View) Enum() *GetMediaAssetRequest_View {
	p := new(GetMediaAssetRequest_View)
	*p = x
	return p
}

func (x GetMediaAssetRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetMediaAssetRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_proto_enumTypes[0].Descriptor()
}

func (GetMediaAssetRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_proto_enumTypes[0]
}

func (x GetMediaAssetRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetMediaAssetRequest_View.Descriptor instead.
func (GetMediaAssetRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{2, 0}
}

type ListMediaAssetRequest_View int32

const (
	ListMediaAssetRequest_VIEW_UNSPECIFIED ListMediaAssetRequest_View = 0
	ListMediaAssetRequest_BASIC            ListMediaAssetRequest_View = 1
	ListMediaAssetRequest_WITH_EDGE_IDS    ListMediaAssetRequest_View = 2
)

// Enum value maps for ListMediaAssetRequest_View.
var (
	ListMediaAssetRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListMediaAssetRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListMediaAssetRequest_View) Enum() *ListMediaAssetRequest_View {
	p := new(ListMediaAssetRequest_View)
	*p = x
	return p
}

func (x ListMediaAssetRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListMediaAssetRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_proto_enumTypes[1].Descriptor()
}

func (ListMediaAssetRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_proto_enumTypes[1]
}

func (x ListMediaAssetRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListMediaAssetRequest_View.Descriptor instead.
func (ListMediaAssetRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{5, 0}
}

type MediaAsset struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            []byte                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	B2Url         string                  `protobuf:"bytes,3,opt,name=b2_url,json=b2Url,proto3" json:"b2_url,omitempty"`
	CaptureTime   *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=capture_time,json=captureTime,proto3" json:"capture_time,omitempty"`
	MimeType      string                  `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Geom          *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=geom,proto3" json:"geom,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAsset) Reset() {
	*x = MediaAsset{}
	mi := &file_entpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAsset) ProtoMessage() {}

func (x *MediaAsset) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAsset.ProtoReflect.Descriptor instead.
func (*MediaAsset) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{0}
}

func (x *MediaAsset) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MediaAsset) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaAsset) GetB2Url() string {
	if x != nil {
		return x.B2Url
	}
	return ""
}

func (x *MediaAsset) GetCaptureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CaptureTime
	}
	return nil
}

func (x *MediaAsset) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaAsset) GetGeom() *wrapperspb.StringValue {
	if x != nil {
		return x.Geom
	}
	return nil
}

func (x *MediaAsset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateMediaAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaAsset    *MediaAsset            `protobuf:"bytes,1,opt,name=media_asset,json=mediaAsset,proto3" json:"media_asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaAssetRequest) Reset() {
	*x = CreateMediaAssetRequest{}
	mi := &file_entpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaAssetRequest) ProtoMessage() {}

func (x *CreateMediaAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateMediaAssetRequest) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMediaAssetRequest) GetMediaAsset() *MediaAsset {
	if x != nil {
		return x.MediaAsset
	}
	return nil
}

type GetMediaAssetRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            []byte                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetMediaAssetRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetMediaAssetRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaAssetRequest) Reset() {
	*x = GetMediaAssetRequest{}
	mi := &file_entpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaAssetRequest) ProtoMessage() {}

func (x *GetMediaAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaAssetRequest.ProtoReflect.Descriptor instead.
func (*GetMediaAssetRequest) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaAssetRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetMediaAssetRequest) GetView() GetMediaAssetRequest_View {
	if x != nil {
		return x.View
	}
	return GetMediaAssetRequest_VIEW_UNSPECIFIED
}

type UpdateMediaAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaAsset    *MediaAsset            `protobuf:"bytes,1,opt,name=media_asset,json=mediaAsset,proto3" json:"media_asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaAssetRequest) Reset() {
	*x = UpdateMediaAssetRequest{}
	mi := &file_entpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaAssetRequest) ProtoMessage() {}

func (x *UpdateMediaAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateMediaAssetRequest) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMediaAssetRequest) GetMediaAsset() *MediaAsset {
	if x != nil {
		return x.MediaAsset
	}
	return nil
}

type DeleteMediaAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaAssetRequest) Reset() {
	*x = DeleteMediaAssetRequest{}
	mi := &file_entpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaAssetRequest) ProtoMessage() {}

func (x *DeleteMediaAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaAssetRequest) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMediaAssetRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ListMediaAssetRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	PageSize      int32                      `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                     `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListMediaAssetRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListMediaAssetRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaAssetRequest) Reset() {
	*x = ListMediaAssetRequest{}
	mi := &file_entpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaAssetRequest) ProtoMessage() {}

func (x *ListMediaAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaAssetRequest.ProtoReflect.Descriptor instead.
func (*ListMediaAssetRequest) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{5}
}

func (x *ListMediaAssetRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMediaAssetRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListMediaAssetRequest) GetView() ListMediaAssetRequest_View {
	if x != nil {
		return x.View
	}
	return ListMediaAssetRequest_VIEW_UNSPECIFIED
}

type ListMediaAssetResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MediaAssetList []*MediaAsset          `protobuf:"bytes,1,rep,name=media_asset_list,json=mediaAssetList,proto3" json:"media_asset_list,omitempty"`
	NextPageToken  string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMediaAssetResponse) Reset() {
	*x = ListMediaAssetResponse{}
	mi := &file_entpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaAssetResponse) ProtoMessage() {}

func (x *ListMediaAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaAssetResponse.ProtoReflect.Descriptor instead.
func (*ListMediaAssetResponse) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{6}
}

func (x *ListMediaAssetResponse) GetMediaAssetList() []*MediaAsset {
	if x != nil {
		return x.MediaAssetList
	}
	return nil
}

func (x *ListMediaAssetResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateMediaAssetsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Requests      []*CreateMediaAssetRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateMediaAssetsRequest) Reset() {
	*x = BatchCreateMediaAssetsRequest{}
	mi := &file_entpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateMediaAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateMediaAssetsRequest) ProtoMessage() {}

func (x *BatchCreateMediaAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateMediaAssetsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateMediaAssetsRequest) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreateMediaAssetsRequest) GetRequests() []*CreateMediaAssetRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateMediaAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaAssets   []*MediaAsset          `protobuf:"bytes,1,rep,name=media_assets,json=mediaAssets,proto3" json:"media_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateMediaAssetsResponse) Reset() {
	*x = BatchCreateMediaAssetsResponse{}
	mi := &file_entpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateMediaAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateMediaAssetsResponse) ProtoMessage() {}

func (x *BatchCreateMediaAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateMediaAssetsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateMediaAssetsResponse) Descriptor() ([]byte, []int) {
	return file_entpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCreateMediaAssetsResponse) GetMediaAssets() []*MediaAsset {
	if x != nil {
		return x.MediaAssets
	}
	return nil
}

var File_entpb_proto protoreflect.FileDescriptor

const file_entpb_proto_rawDesc = "" +
	"\n" +
	"\ventpb.proto\x12\x05entpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x95\x02\n" +
	"\n" +
	"MediaAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06b2_url\x18\x03 \x01(\tR\x05b2Url\x12=\n" +
	"\fcapture_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcaptureTime\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x120\n" +
	"\x04geom\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x04geom\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"M\n" +
	"\x17CreateMediaAssetRequest\x122\n" +
	"\vmedia_asset\x18\x01 \x01(\v2\x11.entpb.MediaAssetR\n" +
	"mediaAsset\"\x98\x01\n" +
	"\x14GetMediaAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x124\n" +
	"\x04view\x18\x02 \x01(\x0e2 .entpb.GetMediaAssetRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"M\n" +
	"\x17UpdateMediaAssetRequest\x122\n" +
	"\vmedia_asset\x18\x01 \x01(\v2\x11.entpb.MediaAssetR\n" +
	"mediaAsset\")\n" +
	"\x17DeleteMediaAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xc6\x01\n" +
	"\x15ListMediaAssetRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x125\n" +
	"\x04view\x18\x03 \x01(\x0e2!.entpb.ListMediaAssetRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"}\n" +
	"\x16ListMediaAssetResponse\x12;\n" +
	"\x10media_asset_list\x18\x01 \x03(\v2\x11.entpb.MediaAssetR\x0emediaAssetList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"[\n" +
	"\x1dBatchCreateMediaAssetsRequest\x12:\n" +
	"\brequests\x18\x01 \x03(\v2\x1e.entpb.CreateMediaAssetRequestR\brequests\"V\n" +
	"\x1eBatchCreateMediaAssetsResponse\x124\n" +
	"\fmedia_assets\x18\x01 \x03(\v2\x11.entpb.MediaAssetR\vmediaAssets2\xa7\x03\n" +
	"\x11MediaAssetService\x12;\n" +
	"\x06Create\x12\x1e.entpb.CreateMediaAssetRequest\x1a\x11.entpb.MediaAsset\x125\n" +
	"\x03Get\x12\x1b.entpb.GetMediaAssetRequest\x1a\x11.entpb.MediaAsset\x12;\n" +
	"\x06Update\x12\x1e.entpb.UpdateMediaAssetRequest\x1a\x11.entpb.MediaAsset\x12@\n" +
	"\x06Delete\x12\x1e.entpb.DeleteMediaAssetRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x04List\x12\x1c.entpb.ListMediaAssetRequest\x1a\x1d.entpb.ListMediaAssetResponse\x12Z\n" +
	"\vBatchCreate\x12$.entpb.BatchCreateMediaAssetsRequest\x1a%.entpb.BatchCreateMediaAssetsResponseB\x1cZ\x1aengram/api/ent/proto/entpbb\x06proto3"

var (
	file_entpb_proto_rawDescOnce sync.Once
	file_entpb_proto_rawDescData []byte
)

func file_entpb_proto_rawDescGZIP() []byte {
	file_entpb_proto_rawDescOnce.Do(func() {
		file_entpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entpb_proto_rawDesc), len(file_entpb_proto_rawDesc)))
	})
	return file_entpb_proto_rawDescData
}

var file_entpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_entpb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_entpb_proto_goTypes = []any{
	(GetMediaAssetRequest_View)(0),         // 0: entpb.GetMediaAssetRequest.View
	(ListMediaAssetRequest_View)(0),        // 1: entpb.ListMediaAssetRequest.View
	(*MediaAsset)(nil),                     // 2: entpb.MediaAsset
	(*CreateMediaAssetRequest)(nil),        // 3: entpb.CreateMediaAssetRequest
	(*GetMediaAssetRequest)(nil),           // 4: entpb.GetMediaAssetRequest
	(*UpdateMediaAssetRequest)(nil),        // 5: entpb.UpdateMediaAssetRequest
	(*DeleteMediaAssetRequest)(nil),        // 6: entpb.DeleteMediaAssetRequest
	(*ListMediaAssetRequest)(nil),          // 7: entpb.ListMediaAssetRequest
	(*ListMediaAssetResponse)(nil),         // 8: entpb.ListMediaAssetResponse
	(*BatchCreateMediaAssetsRequest)(nil),  // 9: entpb.BatchCreateMediaAssetsRequest
	(*BatchCreateMediaAssetsResponse)(nil), // 10: entpb.BatchCreateMediaAssetsResponse
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),         // 12: google.protobuf.StringValue
	(*emptypb.Empty)(nil),                  // 13: google.protobuf.Empty
}
var file_entpb_proto_depIdxs = []int32{
	11, // 0: entpb.MediaAsset.capture_time:type_name -> google.protobuf.Timestamp
	12, // 1: entpb.MediaAsset.geom:type_name -> google.protobuf.StringValue
	11, // 2: entpb.MediaAsset.created_at:type_name -> google.protobuf.Timestamp
	2,  // 3: entpb.CreateMediaAssetRequest.media_asset:type_name -> entpb.MediaAsset
	0,  // 4: entpb.GetMediaAssetRequest.view:type_name -> entpb.GetMediaAssetRequest.View
	2,  // 5: entpb.UpdateMediaAssetRequest.media_asset:type_name -> entpb.MediaAsset
	1,  // 6: entpb.ListMediaAssetRequest.view:type_name -> entpb.ListMediaAssetRequest.View
	2,  // 7: entpb.ListMediaAssetResponse.media_asset_list:type_name -> entpb.MediaAsset
	3,  // 8: entpb.BatchCreateMediaAssetsRequest.requests:type_name -> entpb.CreateMediaAssetRequest
	2,  // 9: entpb.BatchCreateMediaAssetsResponse.media_assets:type_name -> entpb.MediaAsset
	3,  // 10: entpb.MediaAssetService.Create:input_type -> entpb.CreateMediaAssetRequest
	4,  // 11: entpb.MediaAssetService.Get:input_type -> entpb.GetMediaAssetRequest
	5,  // 12: entpb.MediaAssetService.Update:input_type -> entpb.UpdateMediaAssetRequest
	6,  // 13: entpb.MediaAssetService.Delete:input_type -> entpb.DeleteMediaAssetRequest
	7,  // 14: entpb.MediaAssetService.List:input_type -> entpb.ListMediaAssetRequest
	9,  // 15: entpb.MediaAssetService.BatchCreate:input_type -> entpb.BatchCreateMediaAssetsRequest
	2,  // 16: entpb.MediaAssetService.Create:output_type -> entpb.MediaAsset
	2,  // 17: entpb.MediaAssetService.Get:output_type -> entpb.MediaAsset
	2,  // 18: entpb.MediaAssetService.Update:output_type -> entpb.MediaAsset
	13, // 19: entpb.MediaAssetService.Delete:output_type -> google.protobuf.Empty
	8,  // 20: entpb.MediaAssetService.List:output_type -> entpb.ListMediaAssetResponse
	10, // 21: entpb.MediaAssetService.BatchCreate:output_type -> entpb.BatchCreateMediaAssetsResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_entpb_proto_init() }
func file_entpb_proto_init() {
	if File_entpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entpb_proto_rawDesc), len(file_entpb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entpb_proto_goTypes,
		DependencyIndexes: file_entpb_proto_depIdxs,
		EnumInfos:         file_entpb_proto_enumTypes,
		MessageInfos:      file_entpb_proto_msgTypes,
	}.Build()
	File_entpb_proto = out.File
	file_entpb_proto_goTypes = nil
	file_entpb_proto_depIdxs = nil
}
