// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: apps/api/ent/proto/entpb/entpb.proto

package entpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	entpb "engram/api/ent/proto/entpb"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MediaAssetServiceName is the fully-qualified name of the MediaAssetService service.
	MediaAssetServiceName = "entpb.MediaAssetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MediaAssetServiceCreateProcedure is the fully-qualified name of the MediaAssetService's Create
	// RPC.
	MediaAssetServiceCreateProcedure = "/entpb.MediaAssetService/Create"
	// MediaAssetServiceGetProcedure is the fully-qualified name of the MediaAssetService's Get RPC.
	MediaAssetServiceGetProcedure = "/entpb.MediaAssetService/Get"
	// MediaAssetServiceUpdateProcedure is the fully-qualified name of the MediaAssetService's Update
	// RPC.
	MediaAssetServiceUpdateProcedure = "/entpb.MediaAssetService/Update"
	// MediaAssetServiceDeleteProcedure is the fully-qualified name of the MediaAssetService's Delete
	// RPC.
	MediaAssetServiceDeleteProcedure = "/entpb.MediaAssetService/Delete"
	// MediaAssetServiceListProcedure is the fully-qualified name of the MediaAssetService's List RPC.
	MediaAssetServiceListProcedure = "/entpb.MediaAssetService/List"
	// MediaAssetServiceBatchCreateProcedure is the fully-qualified name of the MediaAssetService's
	// BatchCreate RPC.
	MediaAssetServiceBatchCreateProcedure = "/entpb.MediaAssetService/BatchCreate"
)

// MediaAssetServiceClient is a client for the entpb.MediaAssetService service.
type MediaAssetServiceClient interface {
	Create(context.Context, *connect.Request[entpb.CreateMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error)
	Get(context.Context, *connect.Request[entpb.GetMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error)
	Update(context.Context, *connect.Request[entpb.UpdateMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error)
	Delete(context.Context, *connect.Request[entpb.DeleteMediaAssetRequest]) (*connect.Response[emptypb.Empty], error)
	List(context.Context, *connect.Request[entpb.ListMediaAssetRequest]) (*connect.Response[entpb.ListMediaAssetResponse], error)
	BatchCreate(context.Context, *connect.Request[entpb.BatchCreateMediaAssetsRequest]) (*connect.Response[entpb.BatchCreateMediaAssetsResponse], error)
}

// NewMediaAssetServiceClient constructs a client for the entpb.MediaAssetService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMediaAssetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MediaAssetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mediaAssetServiceMethods := entpb.File_apps_api_ent_proto_entpb_entpb_proto.Services().ByName("MediaAssetService").Methods()
	return &mediaAssetServiceClient{
		create: connect.NewClient[entpb.CreateMediaAssetRequest, entpb.MediaAsset](
			httpClient,
			baseURL+MediaAssetServiceCreateProcedure,
			connect.WithSchema(mediaAssetServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[entpb.GetMediaAssetRequest, entpb.MediaAsset](
			httpClient,
			baseURL+MediaAssetServiceGetProcedure,
			connect.WithSchema(mediaAssetServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[entpb.UpdateMediaAssetRequest, entpb.MediaAsset](
			httpClient,
			baseURL+MediaAssetServiceUpdateProcedure,
			connect.WithSchema(mediaAssetServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[entpb.DeleteMediaAssetRequest, emptypb.Empty](
			httpClient,
			baseURL+MediaAssetServiceDeleteProcedure,
			connect.WithSchema(mediaAssetServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[entpb.ListMediaAssetRequest, entpb.ListMediaAssetResponse](
			httpClient,
			baseURL+MediaAssetServiceListProcedure,
			connect.WithSchema(mediaAssetServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		batchCreate: connect.NewClient[entpb.BatchCreateMediaAssetsRequest, entpb.BatchCreateMediaAssetsResponse](
			httpClient,
			baseURL+MediaAssetServiceBatchCreateProcedure,
			connect.WithSchema(mediaAssetServiceMethods.ByName("BatchCreate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mediaAssetServiceClient implements MediaAssetServiceClient.
type mediaAssetServiceClient struct {
	create      *connect.Client[entpb.CreateMediaAssetRequest, entpb.MediaAsset]
	get         *connect.Client[entpb.GetMediaAssetRequest, entpb.MediaAsset]
	update      *connect.Client[entpb.UpdateMediaAssetRequest, entpb.MediaAsset]
	delete      *connect.Client[entpb.DeleteMediaAssetRequest, emptypb.Empty]
	list        *connect.Client[entpb.ListMediaAssetRequest, entpb.ListMediaAssetResponse]
	batchCreate *connect.Client[entpb.BatchCreateMediaAssetsRequest, entpb.BatchCreateMediaAssetsResponse]
}

// Create calls entpb.MediaAssetService.Create.
func (c *mediaAssetServiceClient) Create(ctx context.Context, req *connect.Request[entpb.CreateMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error) {
	return c.create.CallUnary(ctx, req)
}

// Get calls entpb.MediaAssetService.Get.
func (c *mediaAssetServiceClient) Get(ctx context.Context, req *connect.Request[entpb.GetMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error) {
	return c.get.CallUnary(ctx, req)
}

// Update calls entpb.MediaAssetService.Update.
func (c *mediaAssetServiceClient) Update(ctx context.Context, req *connect.Request[entpb.UpdateMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls entpb.MediaAssetService.Delete.
func (c *mediaAssetServiceClient) Delete(ctx context.Context, req *connect.Request[entpb.DeleteMediaAssetRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls entpb.MediaAssetService.List.
func (c *mediaAssetServiceClient) List(ctx context.Context, req *connect.Request[entpb.ListMediaAssetRequest]) (*connect.Response[entpb.ListMediaAssetResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// BatchCreate calls entpb.MediaAssetService.BatchCreate.
func (c *mediaAssetServiceClient) BatchCreate(ctx context.Context, req *connect.Request[entpb.BatchCreateMediaAssetsRequest]) (*connect.Response[entpb.BatchCreateMediaAssetsResponse], error) {
	return c.batchCreate.CallUnary(ctx, req)
}

// MediaAssetServiceHandler is an implementation of the entpb.MediaAssetService service.
type MediaAssetServiceHandler interface {
	Create(context.Context, *connect.Request[entpb.CreateMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error)
	Get(context.Context, *connect.Request[entpb.GetMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error)
	Update(context.Context, *connect.Request[entpb.UpdateMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error)
	Delete(context.Context, *connect.Request[entpb.DeleteMediaAssetRequest]) (*connect.Response[emptypb.Empty], error)
	List(context.Context, *connect.Request[entpb.ListMediaAssetRequest]) (*connect.Response[entpb.ListMediaAssetResponse], error)
	BatchCreate(context.Context, *connect.Request[entpb.BatchCreateMediaAssetsRequest]) (*connect.Response[entpb.BatchCreateMediaAssetsResponse], error)
}

// NewMediaAssetServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMediaAssetServiceHandler(svc MediaAssetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mediaAssetServiceMethods := entpb.File_apps_api_ent_proto_entpb_entpb_proto.Services().ByName("MediaAssetService").Methods()
	mediaAssetServiceCreateHandler := connect.NewUnaryHandler(
		MediaAssetServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(mediaAssetServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	mediaAssetServiceGetHandler := connect.NewUnaryHandler(
		MediaAssetServiceGetProcedure,
		svc.Get,
		connect.WithSchema(mediaAssetServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	mediaAssetServiceUpdateHandler := connect.NewUnaryHandler(
		MediaAssetServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(mediaAssetServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	mediaAssetServiceDeleteHandler := connect.NewUnaryHandler(
		MediaAssetServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(mediaAssetServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	mediaAssetServiceListHandler := connect.NewUnaryHandler(
		MediaAssetServiceListProcedure,
		svc.List,
		connect.WithSchema(mediaAssetServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	mediaAssetServiceBatchCreateHandler := connect.NewUnaryHandler(
		MediaAssetServiceBatchCreateProcedure,
		svc.BatchCreate,
		connect.WithSchema(mediaAssetServiceMethods.ByName("BatchCreate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/entpb.MediaAssetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MediaAssetServiceCreateProcedure:
			mediaAssetServiceCreateHandler.ServeHTTP(w, r)
		case MediaAssetServiceGetProcedure:
			mediaAssetServiceGetHandler.ServeHTTP(w, r)
		case MediaAssetServiceUpdateProcedure:
			mediaAssetServiceUpdateHandler.ServeHTTP(w, r)
		case MediaAssetServiceDeleteProcedure:
			mediaAssetServiceDeleteHandler.ServeHTTP(w, r)
		case MediaAssetServiceListProcedure:
			mediaAssetServiceListHandler.ServeHTTP(w, r)
		case MediaAssetServiceBatchCreateProcedure:
			mediaAssetServiceBatchCreateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMediaAssetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMediaAssetServiceHandler struct{}

func (UnimplementedMediaAssetServiceHandler) Create(context.Context, *connect.Request[entpb.CreateMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entpb.MediaAssetService.Create is not implemented"))
}

func (UnimplementedMediaAssetServiceHandler) Get(context.Context, *connect.Request[entpb.GetMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entpb.MediaAssetService.Get is not implemented"))
}

func (UnimplementedMediaAssetServiceHandler) Update(context.Context, *connect.Request[entpb.UpdateMediaAssetRequest]) (*connect.Response[entpb.MediaAsset], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entpb.MediaAssetService.Update is not implemented"))
}

func (UnimplementedMediaAssetServiceHandler) Delete(context.Context, *connect.Request[entpb.DeleteMediaAssetRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entpb.MediaAssetService.Delete is not implemented"))
}

func (UnimplementedMediaAssetServiceHandler) List(context.Context, *connect.Request[entpb.ListMediaAssetRequest]) (*connect.Response[entpb.ListMediaAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entpb.MediaAssetService.List is not implemented"))
}

func (UnimplementedMediaAssetServiceHandler) BatchCreate(context.Context, *connect.Request[entpb.BatchCreateMediaAssetsRequest]) (*connect.Response[entpb.BatchCreateMediaAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("entpb.MediaAssetService.BatchCreate is not implemented"))
}
